The bindings has been update to use SFML 2RC and SFML Sonkun's bindigs for python. However, there is an exception at importing
In [8]: from pylibrocket import rocket_init
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-8-43d336956cf8> in <module>()
----> 1 from pylibrocket import rocket_init

/usr/lib/python2.7/site-packages/pylibrocket-hg_r32_-py2.7-linux-x86_64.egg/pylibrocket/__init__.py in <module>()
      1 import rocket_init
      2
----> 3 import rocket
      4
      5

ImportError: No module named rocket

In [9]:

there isn't any file called rocket, but rocket_init. I'm not sure if rocket == rocket_init.